# Name of the application.
applicationName: "db"

namespaceOverride: "app"

#Deployment

deployment:
  reloadOnChange: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 1
  env:
    MYSQL_ROOT_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_ROOT_PASSWORD
    MYSQL_DATABASE:
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_DATABASE
    MYSQL_USER:
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_USERNAME
    MYSQL_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWORD
  volumes:
    mysql-storage:
      persistentVolumeClaim:
        claimName: mysql-pvc
  volumeMounts:
      mysql-storage:
         mountPath: /var/lib/mysql/
  image:
    repository: mysql
    tag: "5.7"
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5
    requests:
      memory: 256Mi
      cpu: 0.5
  securityContext:
    fsGroup: 999
  args: ["--ignore-db-dir=lost+found"]
  ports:
  - containerPort: 3306
    name: http
    protocol: TCP
  terminationGracePeriodSeconds: 120

# PV && PVC
persistence:
  enabled: true
  mountPVC: false
  mountPath: "/"
  name: "mysql-pvc"
  accessMode: ReadWriteOnce
  storageClass: "gp2"
  storageSize: 10Gi

# Service 
service:
  ports:
    - port: 3306
      name: http
      protocol: TCP
      targetPort: 3306
  type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 60

