apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-external-secret
  namespace: app
spec:
  refreshInterval: 1h           
  secretStoreRef:
    kind: SecretStore
    name: app-secretstore               
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: dev/app-secret
