apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  namespace: app
  name: app-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: es-sa
            namespace: app
