applicationName: "scheduler"

namespaceOverride: "app"

deployment:
  reloadOnChange: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 1
  envFrom:
    app-configmap:
      type: configmap
      name: app-configmap
    app-secret:
      type: secret
      name: app-secret
  image:
    repository: public.ecr.aws/g7j1x0t3/laravel-app
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5
    requests:
      memory: 128Mi
      cpu: 0.1
  # Security Context at Container Level
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  # Security Context for the pod
  securityContext:
    fsGroup: 2000
  # Command for primary container
  command: ["sh", "-c", "while true; do php artisan schedule:run; sleep 60; done"]
  # Args for primary contaner
  args: []
  terminationGracePeriodSeconds: 120

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 60
