# Name of the application.
applicationName: "app"

namespaceOverride: "app"

deployment:
  reloadOnChange: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 1
  envFrom:
    app-configmap:
      type: configmap
      name: app-configmap
    app-secret:
      type: secret
      name: app-secret
  volumes:
    shared-storage:
      persistentVolumeClaim:
        claimName: shared-pvc
  volumeMounts:
      shared-storage:
         mountPath: /var/www/html
  image:
    repository: public.ecr.aws/g7j1x0t3/laravel-app
    tag: latest
    pullPolicy: IfNotPresent
  # livenessProbe:
  #   enabled: true
  #   failureThreshold: 3
  #   periodSeconds: 10
  #   successThreshold: 1
  #   timeoutSeconds: 1
  #   initialDelaySeconds: 10
  #   httpGet:
  #     path: /
  #     port: 9000
  # Resources to be defined for pod
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5
    requests:
      memory: 128Mi
      cpu: 0.1
  # Security Context at Container Level
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  # Security Context for the pod
  securityContext:
    fsGroup: 2000
  # Command for primary container
  command: []
  # Args for primary contaner
  args: []
  # List of ports for the primary container
  ports:
  - containerPort: 9000
    name: http
    protocol: TCP
  # Graceful termination timeout
  terminationGracePeriodSeconds: 120
  # Container lifecycle management for graceful startup and shutdown procedures
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

# Add Storage volumes to the pods
persistence:
  enabled: true
  mountPVC: false
  mountPath: "/"
  name: "shared-pvc"
  accessMode: ReadWriteOnce
  storageClass: "gp2"
  storageSize: 5Gi

# Service object for servicing pods
service:
  ports:
    - port: 9000
      name: http
      protocol: TCP
      targetPort: 9000
  type: ClusterIP

# Additional ConfigMaps
configMap:
  enabled: true
  files:
    configmap:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_TIMEZONE: UTC
      APP_URL: https://tanphanhue.shop
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      PHP_CLI_SERVER_WORKERS: "4"
      BCRYPT_ROUNDS: "12"
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      SESSION_DRIVER: database
      SESSION_LIFETIME: "120"
      SESSION_ENCRYPT: "false"
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: reverb
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      CACHE_PREFIX: ""
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: "6379"
      MAIL_MAILER: log
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: "2525"
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Laravel
      AWS_DEFAULT_REGION: ap-southeast-1
      AWS_BUCKET: ""
      AWS_USE_PATH_STYLE_ENDPOINT: "false"
      VITE_APP_NAME: Laravel
      REVERB_APP_ID: "1410"
      REVERB_HOST: reverb
      REVERB_PORT: "8080"
      REVERB_SCHEME: http
      VITE_REVERB_HOST: https://tanphanhue.shop
      VITE_REVERB_PORT: "80"
      VITE_REVERB_SCHEME: http
      VITE_REVERB_PATH: /reverb
      APP_CONFETTI_WORDS: "chuc mung|congratulations|congrats|happy new year"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 60
